[project]
name = "supereeg-gpyt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cupy-cuda12x>=13.6.0",
    "nvidia-cuda-nvrtc-cu12",
    "nvidia-cuda-runtime-cu12",
    "future>=1.0.0",
    "h5py>=3.14.0",
    "hypertools>=0.8.2",
    "imageio>=2.37.2",
    "joblib>=1.5.3",
    "matplotlib>=2.2.0",
    "nibabel>=5.3.3",
    "nilearn>=0.12.1",
    "numpy>=1.10.4",
    "pandas>=0.21.1",
    "pytest>=8.4.2",
    "scikit-image>=0.24.0",
    "scikit-learn>=0.18.1",
    "scipy>=0.17.1",
    "seaborn>=0.7.1",
    "tables>=3.9.2",
]

[project.scripts]
supereeg-migrate = "supereeg.cli:main"

[dependency-groups]
dev = [
    "nbsphinx>=0.9.8",
    "numpydoc>=1.10.0",
    "sphinx>=9.1.0",
    "sphinx-gallery>=0.21.0",
    "sphinx-rtd-theme>=3.1.0",
]
