[project]
name = "supereeg-gpyt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cupy-cuda13x>=13.6.0",
    "deepdish>=0.3.7",
    "future>=1.0.0",
    "hypertools>=0.8.2",
    "imageio>=2.37.2",
    "joblib>=1.5.3",
    "matplotlib>=2.2.0",
    "nibabel>=5.3.3",
    "nilearn>=0.12.1",
    "numpy>=1.10.4",
    "pandas>=0.21.1",
    "pytest>=8.4.2",
    "scikit-image>=0.24.0",
    "scikit-learn>=0.18.1",
    "scipy>=0.17.1",
    "seaborn>=0.7.1",
]
